title: MDWG
description: Good practice documentation for the use of ISO19115-3.2018 metadata standard for ANZLIC/ICSM

markdown: kramdown
source-directory: good_practice_guide
kramdown:
  parse_block_html: true

exclude: [README.md]
collections:
  defs:
    output: true
